services:
  postgres:
    image: postgres:18
    container_name: project_demo
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
